[package]
name = "super-ttt-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
super-ttt = { version = "*", path = "../core" }
text_io = "0.1.12"
