[package]
name = "super-ttt"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

description = "An implementation of super tic tac toe"
repository = "https://github.com/ThatXliner/sttt/tree/main/packages/core"
homepage = "https://github.com/ThatXliner/sttt"
readme = "README.md"
keywords = ["engine", "logic", "game"]
categories = ["games"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
